// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace App.ApplicationLayer.ModelsDto
{
    public partial class OrderDto
    {
        public OrderDto()
        {
            OrderItem = new HashSet<OrderItemDto>();
        }

        public Guid Id { get; set; }
        public Guid CustomerId { get; set; }
        public long Number { get; set; }
        public Guid TenantId { get; set; }
        public decimal Sum { get; set; }

        public virtual ICollection<OrderItemDto> OrderItem { get; set; }
    }
}