// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace App.ApplicationLayer.ModelsDto
{
    public partial class ProductDto
    {
        public Guid Id { get; set; }
        public string Code { get; set; }
        public string Tilte { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public Guid TenantId { get; set; }
    }
}