// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace App.ApplicationLayer.ModelsDto
{
    public partial class TenantDto
    {
        public Guid Id { get; set; }
        public string Title { get; set; }
    }
}