// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using App.DomainModelLayer.Products;
using App.Helpers.Domain;
using System;
using System.Collections.Generic;

#nullable disable

namespace App.DomainModelLayer.Models
{
    public partial class Product: IAggregateRoot
    {
        public virtual Guid Id { get; set; }
        public virtual string Code { get; set; }
        public virtual string Tilte { get; set; }
        public virtual string Description { get; set; }
        public virtual decimal? Price { get; set; }
        public virtual Guid? TenantId { get; set; }
        public static Product Create(string code, string tilte, string description, decimal price, Guid tenantId)
        {
            return Create(Guid.NewGuid(),code, tilte, description, price, tenantId);
        }

        public static Product Create(Guid id, string code, string tilte, string description, decimal price, Guid tenanId)
        {
            Product product = new Product()
            {
                Id = id,
                Code = code,
                Tilte = tilte,
                Description = description,
                Price = price,
                TenantId = tenanId,       
            };

            DomainEvents.Raise<ProductCreated>(new ProductCreated() { product = product });

            return product;
        }
    }
}