// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using App.DomainModelLayer.Tenants;
using App.Helpers.Domain;
using System;
using System.Collections.Generic;

#nullable disable

namespace App.DomainModelLayer.Models
{
    public partial class Tenant : IAggregateRoot
    {
        public virtual Guid Id { get; set; }
        public virtual string Title { get; set; }
        public static Tenant Create(Guid id, string title)
        {
            Tenant tenant = new Tenant()
            {
                Id = id,
                Title = title,
            };

            DomainEvents.Raise<TenantCreated>(new TenantCreated() { Tenant = tenant });
            return tenant;
        }
    }
}